### ISSUE TITLE
[PE-D][Tester A] Adding member with similar names in group

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-3/tp#223]
![image.png](https://raw.githubusercontent.com/HongRay/ped/main/files/e1bf0686-32df-4c8d-b42b-a375751de2c4.png)

When calling `add-member bd -cm B`, I only have 1 member called B but it still prompts me to add other members that have the alphabet b in their name.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: HongRay/ped#4

**Comment by benson1029** [comment]
It is an intended behavior.
