### ISSUE TITLE
[PE-D][Tester A] Does not allow the inputs for names with other ethnic groups. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-3/tp#231]
![image.png](https://raw.githubusercontent.com/HongRay/ped/main/files/a304dbed-3868-48aa-a86c-d1e47a705306.png)

Does not allow names from certain ethnic groups e.g. s/o

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: HongRay/ped#8

**Comment by benson1029** [comment]
We encourage users to use nicknames, as described in the user guide. They could choose nicknames without special characters.
