### ISSUE TITLE
[PE-D][Tester D] Groups are still shown with non-existent sample students

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-3/tp#234]
**Bug encountered**
1. Upon deleting all students data, reopen the application
2. The default groups should be created, with the default students

However, this should not be the case because those students no longer exist. This is a data sync issue

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tankh99/ped#2

**Comment by benson1029** [comment]
Cannot reproduce? Can someone try?

**Comment by ivan24004** [comment]
I could reproduce it, seems to be because the groupList doesn't check that the contacts are valid first.
