### ISSUE TITLE
[PE-D][Tester A] Unable to add country code in phone

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-3/tp#243]
![image.png](https://raw.githubusercontent.com/HongRay/ped/main/files/28d9ac46-0cc8-4e35-ade2-37025190fdf8.png)

I am unable to add country code in phone number because only numbers are accepted for the the phone number field. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: HongRay/ped#14

**Comment by benson1029** [comment]
Our target users are NUS students maintaining contact details of NUS coursemates, thus it will be a Singapore phone number.
Moreover, users can just omit the "+" symbol in the phone number.
