### ISSUE TITLE
[PE-D][Tester B] Person name only supports English characters

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-3/tp#246]
![image.png](https://raw.githubusercontent.com/Kaya3842/ped/main/files/fdeab398-7a37-4633-8276-629133eef846.png)

![image.png](https://raw.githubusercontent.com/Kaya3842/ped/main/files/fb93665d-85b5-4b55-8b72-4ca655385933.png)

Adding a name with non-english characters is not allowed

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Kaya3842/ped#4

**Comment by benson1029** [comment]
Our target user is NUS computer science students, so I don't see any need to support other languages.
