### ISSUE TITLE
[PE-D][Tester D] Possible merging of commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-3/tp#247]
Why are commands like "edit-tg-chat-url", "require-skill", "add-member" separate commands? Why not combine them into a single edit group edit command, in a similar format to the "create-group" format

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: tankh99/ped#6

**Comment by benson1029** [comment]
Rationale: These commands are unlikely to be used together.

It is a sensible suggestion though.
