### ISSUE TITLE
[Logic] Change command format for edit and delete

### ISSUE THREAD

**Issue by benson1029** [AY2324S2-CS2103T-F13-3/tp#25]
The new command formats are:
- Edit: `edit NAME [-n NEW_NAME] [-p NEW_PHONE_NUMBER] [-e NEW_EMAIL]`
- Delete: `delete NAME`

Change the current implementation to support these new command formats.

For the NAME search, create a skeleton class for name searching but need not support the substring and/or hash tag notation for now.

**Comment by tzaph** [comment]
Closed as implemented in #79
