### ISSUE TITLE
[PE-D][Tester C] Delete command provides incorrect error message when index is large.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-3/tp#254]
### Description
The UG identifies the format of delete as:
`delete COURSEMATE`
and it produces this bug message for invalid index:

> The courseMate name or index provided is not found!

When the index is even larger like #99999999999999999999999999999999999999999:

> Invalid command format! 
> delete: Deletes the courseMate identified by the index number used in the displayed courseMate list.
> CourseMates can be specified either by name or by the '#' notation.
> Parameters: COURSEMATE

although it is the valid command format.

### Steps to Reproduce

1. Open App
2. Type `delete #99999999999999999999999999999999999999999`

**Expected Behavior**
should produce error message that
> The courseMate name or index provided is not found!

**Actual Behavior**
Invalid command format error displayed.

### Screenshots

![image.png](https://raw.githubusercontent.com/dhlee03/ped/main/files/afb80836-8c96-47a4-9a17-2edd0ba20769.png)

![image.png](https://raw.githubusercontent.com/dhlee03/ped/main/files/f31715f4-d786-4741-88a9-3f0e17226425.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: dhlee03/ped#4

**Comment by benson1029** [comment]
Quoting from course website: If the problems can only happen in case of deliberate sabotage (e.g., user entered a 30-digit telephone number), in which case it should not be considered a bug.
