### ISSUE TITLE
[PE-D][Tester C] add-member command seem to provide a wrong error message with large index.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-3/tp#257]
### Description
The UG identifies the format of add-member as:
`add-member GROUP_NAME -cm COURSEMATE [-cm COURSEMATE]...`

and it produces this bug message for invalid index:

> Some of the specified members could not be found.

When the index is even larger like #99999999999999999999999999999999999999999(unlikely but possible):

> Invalid command format! 
> add-member: Adds CourseMates as members to an existing group. CourseMates can be specified either by name or by the '#' notation.
> Parameters: GROUP_NAME (group must exist) -cm COURSEMATE [-cm COURSEMATE]...
> Example: add-member CS2103T GROUP -cm #1 -cm John Doe.

although it is the valid command format.

### Steps to Reproduce

1. Open App
2. Type `add-member CS2103T -cm #99999999999999999999999999999999999999999`
3. See error

**Expected Behavior**
should produce error message that
> Some of the specified members could not be found.

**Actual Behavior**
command format error displayed

### Screenshots

![image.png](https://raw.githubusercontent.com/dhlee03/ped/main/files/48d23e21-1941-43fb-8da7-a7cb8f792ad5.png)

![image.png](https://raw.githubusercontent.com/dhlee03/ped/main/files/adb2ba60-d589-48de-97ce-9f4b167e534f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: dhlee03/ped#5

**Comment by benson1029** [comment]
Quoting from course website: If the problems can only happen in case of deliberate sabotage (e.g., user entered a 30-digit telephone number), in which case it should not be considered a bug.
