### ISSUE TITLE
[PE-D][Tester E] Telegram group URL made convenient

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-3/tp#261]
Given that tele group links all start with `https://t.me/`, would it be good to automatically help the user fill this up and the user can add the rest of the link accordingly?

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: yeoshuheng/ped#12

**Comment by benson1029** [comment]
Not in scope.
