### ISSUE TITLE
[PE-D][Tester E] Multiple people in a group required to have a single skill.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-3/tp#265]
In some group projects, eg. CS2103, it might be necessary for everyone in the group to be proficient in a certain language (Java for the CS2103 example). Hence, would it be a good idea to allow the specification of number of coursemates needed to be proficient in a given skill to the mark important / unimportant skill feature in the future?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yeoshuheng/ped#14

**Comment by benson1029** [comment]
Not in scope.
